version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx 
    tty: true
    ports:
      - "8080:80"
    networks:
      - nginx-node
    depends_on:
      - app

  db:
   build:
     context: ./database
   command: --innodb-use-native-aio=0
   container_name: db
   restart: always
   tty: true
   expose:
     - "3306"
   ports:
     - "3306:3306"
   environment:
     - MYSQL_DATABASE=desafio-nginx-node-db
     - MYSQL_ROOT_PASSWORD=root
   networks:
     - nginx-node    

  app:
    build: 
      context: ./app
    container_name: app  
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s sh -c "npm install && npm run dev"  
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 40s sh -c "tail -f /dev/null"
    # ports:
    #   - 3000:3000
    volumes:
      - ./app:/usr/src/app
    networks:
      - nginx-node
    depends_on:
      - db  
     

networks:
  nginx-node:
    driver: bridge
    name: nginx-node