version: '3'

services:

  app:
    build: 
      context: ./app
    container_name: app  
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    entrypoint: sh -c "npm install && npm run dev"  
     
